name: Release Workflow

on:
  release:
    types: [published]

jobs:

  lint:
    name: Lint Workflow
    uses: ./.github/workflows/lint.yml

  test:
    name: Test Workflow
    uses: ./.github/workflows/test.yml

  release:
    name: Release Job
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - name: Install
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Package
      run: |
        python -m pip install build --user
        python -m build
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/*
