name: Test Workflow

on:
  workflow_call:

jobs:

  test:
    name: Test Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Test
        run: |
          pip install pytest
          pytest tests
